### ISSUE TITLE
Documentation about name_format

### ISSUE THREAD

**Issue by fRAIKZz** [discord-tickets/docs#17]
Hello,

I'm setting up the bot for my Discord server and noticed that there is a name_format to change the ticket name. Now my questions is, how can I do it so that the custom name will have a counter next to it. 

Example:
Custom-1
Custom-2
etc

Can't find this on the wiki of your documentation, help would be really appreciated.

**Comment by eartharoid** [comment]
Sorry, I forgot to reply earlier.

A category's `name_format` is a string that can contain [these placeholders](https://github.com/discord-tickets/bot/blob/193f351b51a2dfdcd94d604e9409900c456aed53/src/modules/tickets/manager.js#L49-L52):
- `name`/`username`
- `num`/`number`

So for ticket channels to be named `custom-1`, `custom-2` etc, the `name_format` would need to be `custom-{num}`.

**Comment by RooRay** [comment]
> Sorry, I forgot to reply earlier.
> 
> A category's `name_format` is a string that can contain [these placeholders](https://github.com/discord-tickets/bot/blob/193f351b51a2dfdcd94d604e9409900c456aed53/src/modules/tickets/manager.js#L49-L52):
> 
> * `name`/`username`
> * `num`/`number`
> 
> So for ticket channels to be named `custom-1`, `custom-2` etc, the `name_format` would need to be `custom-{num}`.

This might be worth adding to the docs to prevent confusion in the future. Want me to make a PR for it?

**Comment by eartharoid** [comment]
sure
