### ISSUE TITLE
Sponsor Material for MkDocs

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/docs#21]
Use [Material for MkDocs Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) ($10/mo) and use some epic features:

![image](https://user-images.githubusercontent.com/20905071/167305124-bc056d0b-8726-42b2-b123-dd07a99ec5a1.png)

**Comment by RooRay** [comment]
i said my fiver was for the puffins, isaac

**Comment by eartharoid** [comment]
:sweat_smile:

**Comment by eartharoid** [comment]
Most of that is free now but still got Insiders (for just $2)
