### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/docs#23]
and https://github.com/giscus/giscus?

**Comment by RooRay** [comment]
If this were to happen I think it'd require a Discord webhook or something similar for notifications as not many people would read a blog about a Discord bot compared to hearing about it on Discord

**Comment by eartharoid** [comment]
> If this were to happen I think it'd require a Discord webhook or something similar for notifications as not many people would read a blog about a Discord bot compared to hearing about it on Discord

That's a good idea, although aside from comparisons which will probably all be published at once, the blog will mostly be for changelogs which I'll announce anyway.

It's probably not as effective as Discord messages but there is a mail list for notifications: https://blog.discordtickets.app/#/portal.
