### ISSUE TITLE
[BUG] Link still broken

### ISSUE THREAD

**Issue by jakub-zip** [discord-tickets/docs#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Found a broken link here (https://discordtickets.app/self-hosting/installation/docker/#docker-compose), the environment varibles button, I wanted to fork and fix it but I noticed that it has been already fixed here:
https://github.com/discord-tickets/docs/commit/e021e3ec01b9339def6c3a06c57dd867c9536f68
but on the live website the bug is still present.

### Environment

```markdown
- OS:
- Node:
- NPM:
- Bot:
```

**Comment by RooRay** [comment]
I see that new builds of the website are not running as they should, hence why the fix was never deployed. Sorry about that.

I've passed this on to Earth for fixing, thanks for the report!

**Comment by eartharoid** [comment]
The last successful build was for the previous commit (https://github.com/discord-tickets/docs/commit/8639fa8420f2667a2ea87ed24229bad781be8062), but it has been failing since due to an unrelated error.
I've updated *Material for MkDocs Insiders* and builds are succeeding now.

Thanks.
